### PR TITLE
Feature entering

### PR DESCRIPTION
**Pull request by Darkdah**
Added the following PatternFormatter markers:
1. "%D" to log a date/time that features millisecond precision
2. "%t" to log the current thread id as a hexadecimal
3. "%T" to log the name of the current thread or GCD queue

Finalized this iteration of the entering and exiting function logging, including the logging of arguments and return values and added test cases for my additions.

### CODE REVIEW

**Comment by jduquennoy** [comment]
Hi Darkdah,

Thanks for this contribution !
I will read it carefully as soon as I can find some free time :-).

One quick note though : 
I originally decided to use strftime to format dates for two reasons :
- availability on Linux (I want that library to be available on Linux, as soon as I can find time to do that)
- performance issue : NSDateFormatter is not exactly fast.

On the performance issue, I realized since that the slowest part of NSDateFormatter is the creation of the object (approximately 10 times slower than the formatting itself according to my tests).
It would be great, to create an NSDateFormatter only once per PatternFormatter object, to speed things up.

To test the performances of the date formatting, I invite you to add and run tests in PatternFormatterPerformanceTests.swift. Here are some sample tests that could be used :

```
func testStrftimeDateFormatterPerformance() {
  let formatter = try! PatternFormatter(identifier:"testFormatter", pattern: "%d{'format':'%m %d %y %k:%M'}")
  let info: LogInfoDictionary = [
    LogInfoKeys.LoggerName: "nameOfTheLogger",
    LogInfoKeys.LogLevel: LogLevel.Info
  ]

  self.measureBlock() {
    for _ in 1...10000 {
      formatter.format("Log message", info: info)
    }
  }
}

func testCocoaDateFormatterPerformance() {
  let formatter = try! PatternFormatter(identifier:"testFormatter", pattern: "%D{'format':'dd MM yyyy HH:mm'}")
  let info: LogInfoDictionary = [
    LogInfoKeys.LoggerName: "nameOfTheLogger",
    LogInfoKeys.LogLevel: LogLevel.Info
  ]

  self.measureBlock() {
    for _ in 1...10000 {
      formatter.format("Log message", info: info)
    }
  }
}
```

I realized that the code of perf tests was not up to date, I pushed a commit to fix that.

Jerome

**Comment by Darkdah** [comment]
Hello Jerome,

after reading your feedback I implemented the following:
- Improved the performance of the '%D' pattern marker by not creating the NSDateFormatter object every time, but only once per PatternFormatter object. The performance of '%D' is now about as fast as '%d'.
- Improved portability by replacing NSDate().timeIntervalSince1970 with my own implementation getSecondsSince1970(), which is based on gettimeofday()
- Added a few more performance tests to PatternFormatterTests.swift

Regarding the current usage of NSDateFormatter under portability aspects: I think we should wait and see what functionality a common swift standard library will bring and evaluate our options once that is available.
- Darkdah

**Comment by Darkdah** [comment]
Hello Jerome,

there is one more remark I want to make:
I'm not exactly happy about the arguments "dumpArgs" and "withTypeInfo" in the entering and exiting methods, I would rather want to add them as a config parameter for the Logger in form of an enum with the members "DumpArgs" and "DumpArgsWithTypeInfo".

I implemented the entering() and exiting() methods to get as much logging output as possible in situations where no debugger can be used, i.e. on the system of a customer. Thus the option to dump the arguments. But right now to tune those settings one would have to recompile and redeploy instead of simply making changes to a config file.

So if you agree with me I'd like to make this change before you accept the pull request (that way I don't have to change the signature of those methods after you accepted this pull request).

-Darkdah

**Comment by Darkdah** [comment]
Hello Jerome,

I added all the functionality I had in mind for now. If you like the changes it'd be great if you'd accept the pull request.

-Darkdah

**Comment by jduquennoy** [comment]
Hi Markus,

I have not forgotten you :-).
I'm having some pretty intense time currently between my work and an associative involvement. I have very few free time, that is why I cannot spend as much time as I would like on Log4swift.

But don't worry, this should not last more than one or two weeks :-).

Bye,

Jerome

> Le 21 avr. 2016 à 08:51, Markus Arndt notifications@github.com a écrit :
> 
> Hello Jerome,
> 
> I added all the functionality I had in mind for now. If you like the changes it'd be great if you'd accept the pull request.
> 
> -Darkdah
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub https://github.com/jduquennoy/Log4swift/pull/7#issuecomment-212771037

Jérôme Duquennoy

---

clef GPG : http://jerome.duquennoy.fr/gpg/jduquennoy.gpg
md5 : c0ff5a8bca033eade512374db18ecb38

**Comment by jduquennoy** [comment]
Hi Markus,

Sorry for the long delay, that was much longer than I originally expected.
I finally had time to study your pull request.

I split it in three parts :

### NSDateFormatter based marker in the PatternFormatter

I love that.
I would propose a deeper change to the PatternFormatter to do that though :
In the current PatternFormatter, there is just a dictionary of closures, all parameters are supposed to be applied at formatting time.
Now, we need to create an NSDateFormatter object at parsing time, which means, after all, customizing the bloc.

So I propose to replace the closures dictionary by a factory method, that will return a closure, that might be customized depending on the parameters of the marker.
This will avoid adding a parameters to all closures, when it is only needed by one of them.
I posted this proposal on the cocoaDateFormatter branch of the repo, mostly based on a copy-past of your proposal, with this proposed change.

If you agree with that solution, I'll merge that branch in master.

### Thread info in the PatternFormatter

That is great too.
There is one problem though with your proposal : the thread ID or thread name is grabbed at formatting time. If the formatter is used by a threaded logger, then, the thread information will be irrelevent.
Those thread information has to be moved to the Logger class, in the two internal log methods, where most log infos are grabbed. The performance of getting those info doesn't seem to be a problem with the two methods you wrote.

### Specific entry / exit log methods

I am not very fond of that feature for two reason :
- it looks like a debug feature rather than a log feature ;
- it is not straitforward to use : the dev has to build a list of the arguments its method has received, which makes it a not very appealing solution ;

I have the feeling that this does not belong to the logging library. I think the best way to go for that would be to have an utility method in your project that will receive the list of arguments, the logger to use, and request a log of a closure, that will format the message. This closure can use the threshold level of the logger to determine wether it should print all arguments or not.

**Comment by Darkdah** [comment]
Hello Jerome,

many thanks for your feedback.

**regarding NSDateFormatter based marker in the PatternFormatter:**
Your change looks fine to me, feel free to merge it. However I'd like to remind you of your message from Apr 14, in which you correctly mentioned that the creation of NSDateFormatter objects is slow. And if I interpret your changes correctly you ignore your own advice and create a NSDateFormatter object for every message. Did you change your mind regarding the performance impact?

**regarding Thread info in the PatternFormatter:**
I'll see that I reimplement that feature based on your suggestion asap once you merged your pull request.

**regarding Specific entry / exit log methods:**
Looks like we are of opposite opinions in this case, because I find the feature extremely useful.
The company I work for uses log4net as logging framework. I added these features to it years ago and since then they helped us greatly several times when analyzing server side problems on customer production systems. On production systems you usually don't find any development/debugging tools. Furthermore most of the time a problem only shows up with the customer data, but for obvious reason you can't just take their database with you to analyze the problem in an environment where you can debug. So you have to resort to logging. Why can't a logger offer built-in functions to help you with that?
Anyway, if you still don't like that addition once you read this I'll find some other way to implement it for myself. However neither you nor anybody else will then participate from it.

-Markus

**Comment by jduquennoy** [comment]
Hi Markus,

**Regarding NSDateFormatter**
No no, I'm only creating the date formatter once per marker : when the closureForMarker method is called for "D", it creates an NSDateFormatter variable, that is then used in generatedClosure. Thus, generatedClosure will retain the dateFormatter, and use it every time it is executed.
I checked with the perf tests that it is equivalent to the strftime version

I'll merge the branch asap.
And next step, once I'll have log4swift ready for Linux and if the open source swift version of NSDateFormatter is as fast as the cocoa one, I'll think about getting rid of the strftime version.

**Regarding the entry / exit logs**
I completely understand that it is valuable for you. But I have the feeling that this is specific, notably because the format of the description string is hard coded, while it can change in multiple ways, depending on what your needs are. in my current job, at least, I know that if we had to use that, we would have to format things differently depending on the nature of the argument and the context.
So in the swift world, I have the feeling that this is a nice opportunity to leverage some pretty cool features available in swift : 
- using a closure to format your description message. Here is an exemple of what I think it could look like : 

```
class SampleClass {
  let logger = LoggerFactory.sharedInstance.getLogger("sampleLogger")

  func methodWithPlentyOfArgs(arg1: String, arg2: String, arg3: String) {
    self.logger.debug { return descriptionForArguments([arg1, arg2, arg3], self.logger.willIssueLogForLevel(.Trace)) }
  }
}

let descriptionForEntry = { (arguments: Array<AnyObject>, printValues: Bool) -> String in
  return "place here the composition of the entry log"
}
```
- Add an extension to the Logger class, that exposes the specialised logging method

Would one of those solution (or a mix of both) fit your need, internally ?

**Comment by Darkdah** [comment]
Hello Jerome,

you are right, having no way to customize the logging output when using the entering/exiting functionality is a problem I didn't consider.

From my point of view you can close my pull request for now as the useful parts of it have already been implemented by your changes or will be reimplemented by me soon.

I'll see if I can come up with a general approach for tracing the program flow and logging of parameters and return values. If I do we can eventually add it to the project, if not everybody who needs such a feature will have to implement his own version based on his preferences.

-Markus

**Comment by jduquennoy** [comment]
Ok, I'm closing it then.

Thanks :-)

Jerome

**Pull request closed without merging**
