### PR TITLE
Extended interface for inheritance `Appender` class.

### PR DESCRIPTION
**Pull request by dukhovnyi**
Extended inheritance interface and as a result added a possibility to create custom `Appender`.
____

Currently, I want to create custom `Appender` and configure it from the config file but can't do this because `update` method is internal and I can't to override it in my subclass.
So my proposal is to make the method as `open` and as result possible to override this method in a subclass.

### CODE REVIEW

**Comment by serges147** [comment]
@jduquennoy Hello! Could you please take a look at what @dukhovnyi have proposed? IMHO looks very reasonable. Thanks!

**Comment by jduquennoy** [comment]
Hi guys,
Sorry for the delay, I was under heavy load those days, I forgot to handle that pull request.
It definitely makes sense, I'll merge it right now.
Thanks for the PR, and thanks for the reminder :-).

**Comment by serges147** [comment]
Thank you!

**Comment by dukhovnyi** [comment]
Thanks. 👍

**Pull request merged**
