### PR TITLE
Added the following PatternFormatter markers:

### PR DESCRIPTION
**Pull request by Darkdah**
%t to log the current thread id as a hexadecimal
%T to log the name of the current thread or GCD queue

### CODE REVIEW

**Comment by Darkdah** [comment]
Hello Jerome,

here as promised the revised implementation of the thread id and thread name PatternFormatter markers.

-Markus

**Comment by jduquennoy** [comment]
Hi Markus, I may suggest a few more changes in that pull request (I hope I'm not beginning to be boring :-) ) : 
- The method to get the thread ID does not need to be extracted in a C file : it is possible to write it in swift and benefit from the advantages of the language : 

```
internal func currentThreadId() -> UInt64 {
  let machThread = pthread_mach_thread_np(pthread_self())
  var info = thread_identifier_info_data_t()
  var infoCount = mach_msg_type_number_t(sizeof(thread_identifier_info_data_t) / sizeof(UInt64))
  var threadId: UInt64 = 0

  withUnsafeMutablePointer(&info) { infoPointer in
    let result = thread_info(machThread, thread_flavor_t(THREAD_IDENTIFIER_INFO), thread_info_t(infoPointer), &infoCount)
    if result == KERN_SUCCESS {
      threadId = info.thread_id
    }
  }

  return threadId
}
```
- in the tests, I would suggest two changes : 
  - Using a loop to wait until the threaded method is executed is risky : in case of a bug, it can cause infinite loops. For tests in multithread environment, XCTest provides expectations, that are pretty handy. You declare them at the beginning of the test, fulfill them in the threaded methods, and wait for all expectations to be fulfilled before the end of the test, with a timeout and and optional error handler.
  - In the second test (testLoggerLogsGCDQueueNameAndId), I think the test can be made simpler (more linear to read) by issuing the log in the dispatched closure rather than using an the inner class.

With those two changes, the second test would become : 

```
func testLoggerLogsGCDQueueNameAndId() {
  let expectation = self.expectationWithDescription("logIssued")
  var threadId: UInt64 = 0
  let logger = Logger(identifier: "test.logger", level: LogLevel.Debug, appenders: [appender])
  let formatter = try! PatternFormatter(identifier:"testFormatter", pattern: "%t %T %m")
  let appender = MemoryAppender()
  appender.thresholdLevel = .Debug
  appender.formatter = formatter

  let gcdQueue = dispatch_queue_create("someQueueName", DISPATCH_QUEUE_CONCURRENT)
  dispatch_async(gcdQueue) {
    threadId = currentThreadId()

    // Execute
    logger.debug("ping")

    expectation.fulfill()
  }

  waitForExpectationsWithTimeout(0.5, handler: nil)

  // Validate
  let hexaThreadId = String(myInstance.threadId, radix: 16, uppercase: false)
  XCTAssertEqual(myInstance.logMessage, "\(threadId) someQueueName ping")
}
```

Does these changes seem sensible to you ?

Jerome

**Comment by Darkdah** [comment]
Hello Jerome,

thanks for your suggestions. For your info I come from a Pascal -> Modula II -> C -> C++ -> Java legacy and did nothing else but C# and .NET in the past 9 years. I just started learning to program in Swift (and Cocoa and Xcode) as a hobby a few months ago, so there are new things to learn every day and my Swift code most likely will be far from perfect :)

I'll implement these suggested changes tomorrow.

-Markus

**Comment by Darkdah** [comment]
Hello Jerome,

all your suggestions should be implemented now.

-Markus

**Comment by jduquennoy** [comment]
Hi Markus,

I merged your pull request, but did a small fix after that : I realized that one of my suggestion was wrong : the infoCount variable in the method I proposed to fetch the thread ID is correct (it returns 3, and the structure contains 3 variables), but this value is checked against a boggous one in XNU.
They computed the number of argument considering that the variables are natural_t (32 bits), when in swift, they are declared as UInt64 (64 bits). So we send anything else that 6, we end up with a zero threadID.

I will send a bug report on that, and I added a condition in the test, so that if ever they fix it causing log4swift to get a zero thread ID, a test will fail.

Thanks for your contribution !

**Pull request merged**
